from cyk_parser import grammar

# Here is the demo file, wanted to get some live demos during class,
# but ran out of time, Uncomment the grammar and its corresponding 
# parse method to check it out. Look at the console output to see the 
# parse table and whether or not the input string is in the language
# generated by the grammar G

# If you want to compare output parse table look at this implementation:
# https://www.xarg.org/tools/cyk-algorithm/
# Only difference is the tool doesn't remove duplicate non terminals in the same
# table cell from its parse tree

# usage:
# python3 cyk_demo.py

# g_one = grammar('test_grammar_one.txt')
# Corresponding grammar
    # S -> AB
    # A -> CD|CF
    # B -> c|EB
    # C -> a
    # D -> b
    # E -> c
    # F -> AD
# g_one.parse('aaabbbcc')

g_two = grammar('test_grammar_two.txt')
# Corresponding grammar
    # S -> AB|BC
    # A -> BA|a
    # B -> CC|b
    # C -> AB|a
g_two.parse('baaba')

# g_three = grammar('test_grammar_three.txt')
# Corresponding grammar
    # S -> XS|TY|AT|BT|ZR|a|b
    # F -> TY|AT|BT|a|b
    # T -> AT|BT|a|b
    # X -> TP
    # Y -> UF
    # Z -> LS
    # A -> a
    # B -> b
    # P -> x
    # U -> t
    # L -> l
    # R -> r
# g_three.parse('bxataa')

# Add your own grammar for fun the file is empty!
# g_four = grammar('test_grammar_from_class.txt')
# Corresponding grammar
# g_three.parse('')
print('Exiting progam')

